version: "3.8"
services:
    web:
        build:
            context: C:\Users\aiz\redentor\tako-cli\examples\01-simple-web
            dockerfile: Dockerfile
        container_name: simple-web_web_dev
        ports:
            - 3000:3000
        environment:
            DEV_MODE: "true"
            ENVIRONMENT: development
            NODE_ENV: production
        volumes:
            - C:\Users\aiz\redentor\tako-cli\examples\01-simple-web:/app
            - /app/node_modules
        restart: unless-stopped
networks:
    tako-dev:
        driver: bridge
