version: "3.8"
services:
    app:
        build:
            context: C:\Users\aiz\redentor\tako-cli\examples\09-nextjs-todos
            dockerfile: Dockerfile
        container_name: nextjs-todos_app_dev
        ports:
            - 3000:3000
        environment:
            DATABASE_PATH: /app/data/todos.db
            DEV_MODE: "true"
            ENVIRONMENT: development
            NODE_ENV: production
        volumes:
            - C:\Users\aiz\redentor\tako-cli\examples\09-nextjs-todos:/app
            - /app/node_modules
        restart: unless-stopped
networks:
    tako-dev:
        driver: bridge
